export const terms = {
  "Fresh Apples": null,
  "Fresh Bananas": null,
  "Fresh Berries": null,
  "Fresh Grapes": null,
  "Fresh Lemons": null,
  "Fresh Lime": null,
  "Fresh Melons": null,
  "Fresh Nectarines": null,
  "Fresh Oranges": null,
  "Fresh Peaches": null,
  "Fresh Pears": null,
  "Fresh Plums": null,
  "Fresh Strawberries": null,
  "Fresh Watermelon": null,
  "Fresh Asparagus": null,
  "Fresh Broccoli": null,
  "Fresh Cabbage": null,
  "Fresh Carrots": null,
  "Fresh Cauliflower": null,
  "Fresh Celery": null,
  "Fresh Corn": null,
  "Fresh Garlic": null,
  "Fresh Lettuce": null,
  "Fresh Mushrooms": null,
  "Fresh Onions": null,
  "Fresh Peppers": null,
  "Fresh Potato": null,
  "Fresh Squash": null,
  "Fresh Sweet Potato": null,
  "Fresh Tomatoes": null,
  "Fresh Zucchini": null,
  "Canned Cherries": null,
  "Canned Mixed Fruit": null,
  "Canned Peaches": null,
  "Canned Pears": null,
  "Canned Pineapples": null,
  "Canned Asparagus": null,
  "Canned Carrots": null,
  "Canned Corn": null,
  "Canned Greenbeans": null,
  "Canned Peas": null,
  "Canned Potatoes": null,
  "Canned Tomatoes": null,
  "Canned Baked Beans": null,
  "Canned Butter Beans": null,
  "Canned Green Beans": null,
  "Canned Kidney Beans": null,
  "Canned Pinto Beans": null,
  "Canned PorkNBeans": null,
  "Canned String Beans": null,
  "Frozen Broccoli": null,
  "Frozen Carrots": null,
  "Frozen Corn": null,
  "Frozen Dinners": null,
  "Frozen French Fries": null,
  "Frozen Ice Cream": null,
  "Frozen Mixed Veg.": null,
  "Frozen Peas": null,
  "Frozen Pizza": null,
  "Frozen Tater Tots": null,
  "Ground Beef": null,
  Hamburger: null,
  "Roast Beef": null,
  "Beef Steaks": null,
  "Boneless Chicken Breast": null,
  "Chicken Breast with Bone": null,
  "Chicken Legs": null,
  "Whole Chicken": null,
  "Chicken Wings": null,
  "Deli Ham": null,
  "Deli Roast Beef": null,
  "Deli Smoked Turkey": null,
  "Deli Turkey": null,
  Bacon: null,
  "Pork Chops": null,
  Ham: null,
  "Pork Roast": null,
  "Pork Sausage": null,
  Crabmeat: null,
  Fish: null,
  Scallops: null,
  Shrimp: null,
  "Canned Chicken": null,
  "Corned Beef": null,
  "Canned Ham": null,
  "Canned Salmon": null,
  "Canned Tuna": null,
  "Vienna Sausage": null,
  Seasonings: null,
  "Celery Salt": null,
  Cinnamon: null,
  "Garlic Powder": null,
  "Garlic Salt": null,
  Ginger: null,
  Nutmeg: null,
  "Onion Powder": null,
  Oregano: null,
  Paprika: null,
  Parsley: null,
  Pepper: null,
  Salt: null,
  Condiments: null,
  "BBQ Sauce": null,
  Honey: null,
  Horseradish: null,
  Jelly: null,
  Ketchup: null,
  Mayonnaise: null,
  Mustard: null,
  "Peanut Butter": null,
  Salsa: null,
  "Soy Sauce": null,
  Syrup: null,
  Worcestershire: null,
  Miscellaneous: null,
  Batteries: null,
  Cards: null,
  "Camera Film": null,
  "Light Bulbs": null,
  "VCR Tapes": null,
  Oils: null,
  "Cooking Spray": null,
  "Olive Oil": null,
  "Vegetable Oil": null,
  Dressings: null,
  "Blue Cheese Dressing": null,
  "French Dressing": null,
  "Italian Dressing": null,
  "Ranch Dressing": null,
  "Thousand Island Dressing": null,
  Snacks: null,
  Candy: null,
  Cookies: null,
  Crackers: null,
  Nuts: null,
  Popcorn: null,
  "Potato Chips": null,
  Pretzels: null,
  Raisins: null,
  Soups: null,
  "Chicken and Rice Soup": null,
  "Chicken Noodle Soup": null,
  "Cream of Broccoli Soup": null,
  "Cream of Celery Soup": null,
  "Cream of Chicken Soup": null,
  "Cream of Mushroom Soup": null,
  "Tomato Soup": null,
  "Vegetable Soup": null,
  "Vegetable Beef Soup": null,
  "Vegetable Chicken Soup": null,
  Breads: null,
  Biscuits: null,
  Buns: null,
  "Hamburger Buns": null,
  "Hot Dog Buns": null,
  "French Bread": null,
  "Italian Bread": null,
  Rolls: null,
  "Wheat Bread": null,
  "White Bread": null,
  Beverages: null,
  Coffee: null,
  Juice: null,
  Milk: null,
  "Orange Juice": null,
  "Soft Drinks": null,
  "Sports Drinks": null,
  Tea: null,
  Water: null,
  Dairy: null,
  Butter: null,
  Cheese: null,
  "Cottage Cheese": null,
  "Cream Cheese": null,
  Creamer: null,
  Eggs: null,
  Margarine: null,
  "Sliced Cheese": null,
  "Sour Cream": null,
  Yogurt: null,
  "Italian Foods": null,
  "Spaghetti Sauce": null,
  "Tomato Paste": null,
  "Tomato Sauce": null,
  "Angel Hair Pasta": null,
  "Elbow Macaroni": null,
  "Lasagne Pasta": null,
  "Rotelle Pasta": null,
  "Shells Pasta": null,
  "Spaghetti Pasta": null,
  "Vemicelli Pasta": null,
  "Mexican Foods": null,
  "Green Chili": null,
  "Refried Beans": null,
  "Spanish Rice": null,
  Tacos: null,
  "Tortillias - Corn": null,
  "Tortillias - Flour": null,
  Packaged: null,
  "Baking Powder": null,
  "Baking Soda": null,
  "Brown Sugar": null,
  "Brownie Mix": null,
  "Cake Mix": null,
  Cereal: null,
  Cocoa: null,
  Cornstarch: null,
  Flour: null,
  Jello: null,
  Oatmeal: null,
  "Pancake Mix": null,
  Rice: null,
  Sugar: null,
  "Vanilla Extract": null,
  "Breakfast Cereals": null,
  "Baby Items": null,
  "Baby Diapers": null,
  "Baby Formula": null,
  "Baby Lotion": null,
  "Baby Oil": null,
  "Baby Rash Cream": null,
  "Baby Shampoo": null,
  "Baby Wipes": null,
  "Baby Food": null,
  "Apple Juice": null,
  Applesauce: null,
  Bananas: null,
  Beef: null,
  Carrots: null,
  Chicken: null,
  Dinners: null,
  Greenbeans: null,
  "Mixed Veg.": null,
  Peaches: null,
  Pears: null,
  Squash: null,
  "Sweet Potato": null,
  Veal: null,
  Medicine: null,
  Antiacid: null,
  Bandaids: null,
  "Cough Drops": null,
  "First Aid Cream": null,
  "Hydrogen Peroxide": null,
  "Pain-Reliever": null,
  "Rubbing Alcohol": null,
  "Pet Items": null,
  "Dog Food": null,
  "Cat Food": null,
  "Cat Litter": null,
  Toiletries: null,
  "Anti-Bacterial Soap": null,
  Deodorant: null,
  Floss: null,
  Lotion: null,
  Mouthwash: null,
  "Petroleum Jelly": null,
  Razors: null,
  Shampoo: null,
  "Shaving Cream": null,
  Soap: null,
  Toothbrush: null,
  Toothpaste: null,
  Paper: null,
  Foil: null,
  "Freezer Bags": null,
  "Kitchen Bags": null,
  "Paper Towels": null,
  "Plastic Wrap": null,
  "Sandwich Bags": null,
  "Storage Bags": null,
  Tissue: null,
  "Toilet Paper": null,
  "Trash Bags": null,
  "Yard Bags": null,
  Cleaners: null,
  Bleach: null,
  Broom: null,
  "Dishwasher Detergent": null,
  "Dishwashing Soap": null,
  "Dryer Sheets": null,
  "Furniture Polish": null,
  "Glass Cleaner": null,
  "Laundry Detergent": null,
  Mop: null,
  "Scrub Brush": null,
  Sponges: null,
  "Toilet Bowl Cleaners": null,
  Towels: null
};

const termKeys = Object.keys(terms);

const nonVeganSearch = /beef|milk|chicken|steak|turkey|ham|pork|crab|shrimp|egg|yogurt|veal|cream|fish|scallops|dairy|tacos|bacon/gi;

const stableSearch = /pasta|beans|rice|sauce|baking|sugar|mix(?!ed)|cereal|potato|squash|oatmeal|cocoa|cornstarch|jello|macaroni|drinks|coffee|pretzels|raisins|candy|olive|spray|syrup|honey|vienna|flour|food|tomato paste|butter|margarine|water|tea|pop|nut|juice|bever|snacks|oils|dinn/i;

const breadSearch = /bread|bun|bisc|rolls|tortil|crackers|cookies/i;

const condimentsSearch = /dressing|ketchup|catsup|mayonaise|salsa|mustard|jelly|horse|condi|mayon|worce/i;

const spicesSearch = /salt|pepper(?!s)|oregano|paprika|parsley|nutmeg|powder|cinnamon|extract|season|ginger|green/i;

const fresh = termKeys.filter(term => term.includes("Fresh"));

const produce = fresh.map(term => term.replace("Fresh", "").trim());

const soup = termKeys.filter(term => term.includes("Soup"));

const cans = termKeys.filter(term => term.includes("Canned"));

const frozen = termKeys.filter(term => term.includes("Frozen"));

const preVegan = termKeys.filter(term => term.search(nonVeganSearch) > -1);

const preVegan2 = preVegan.filter(
  term => term.search(/soup|sham|bun|canned/i) === -1
);

const nonVegan = preVegan2.filter(
  term => term.search(/frozen|first|shav/i) === -1
);

const bread = termKeys.filter(term => term.search(breadSearch) > -1);

const cheese = termKeys.filter(term => term.search(/cheese(?!\sdress)/i) > -1);

const prestable = termKeys.filter(term => term.search(stableSearch) > -1);

const stable = prestable.filter(
  term => term.search(/canned|frozen|soup|baby|sour|petro/i) === -1
);

const canned = [...cans, ...soup];

const condiments = termKeys.filter(term => term.search(condimentsSearch) > -1);

const prespices = termKeys.filter(term => term.search(spicesSearch) > -1);

const spices = prespices.filter(term => term.search(/canned/i) === -1);

const groceries = [
  ...frozen,
  ...nonVegan,
  ...bread,
  ...cheese,
  ...stable,
  ...canned,
  ...condiments,
  ...spices,
  ...produce
];

const house = termKeys.filter(term => !groceries.includes(term));

const household = house.filter(term => term.search(/veg|fresh/i) === -1);

export const categories = [
  nonVegan,
  bread,
  cheese,
  stable,
  condiments,
  produce,
  canned,
  spices,
  frozen,
  household
];
